import type { ProjectState } from './types';

export const PROJECT_STATES = [
  'CREATED',
  'ANALYZING_OPPORTUNITY',
  'TOPIC_SELECTED',
  'RESEARCHING',
  'SCRIPTING_PROVISIONAL',
  'STORYBOARD_PROVISIONAL',
  'WAITING_FOR_DOWNLOADS',
  'INGESTING_MEDIA',
  'VERIFYING_FOOTAGE',
  'FINALIZING_SCRIPT',
  'GENERATING_VOICE',
  'BUILDING_TIMELINE',
  'RENDERING_DRAFT',
  'QC_DRAFT',
  'RENDERING_FINAL',
  'QC_FINAL',
  'UPLOADING_PRIVATE',
  'WAITING_YOUTUBE_PROCESSING',
  'WAITING_FINAL_APPROVAL',
  'SCHEDULED',
  'PUBLISHED',
  'ANALYTICS_ACTIVE',
  'PAUSED',
  'BLOCKED_EXCEPTION',
  'AWAITING_MANUAL_STUDIO_ACTION',
  'CANCELLED',
  'FAILED',
  'ARCHIVED'
] as const satisfies readonly ProjectState[];

const entries: Array<[ProjectState, readonly ProjectState[]]> = [
  ['CREATED', ['ANALYZING_OPPORTUNITY', 'CANCELLED', 'FAILED']],
  ['ANALYZING_OPPORTUNITY', ['TOPIC_SELECTED', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['TOPIC_SELECTED', ['RESEARCHING', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['RESEARCHING', ['SCRIPTING_PROVISIONAL', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['SCRIPTING_PROVISIONAL', ['STORYBOARD_PROVISIONAL', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['STORYBOARD_PROVISIONAL', ['WAITING_FOR_DOWNLOADS', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['WAITING_FOR_DOWNLOADS', ['INGESTING_MEDIA', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['INGESTING_MEDIA', ['VERIFYING_FOOTAGE', 'WAITING_FOR_DOWNLOADS', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['VERIFYING_FOOTAGE', ['FINALIZING_SCRIPT', 'WAITING_FOR_DOWNLOADS', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['FINALIZING_SCRIPT', ['GENERATING_VOICE', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['GENERATING_VOICE', ['BUILDING_TIMELINE', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['BUILDING_TIMELINE', ['RENDERING_DRAFT', 'RENDERING_FINAL', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['RENDERING_DRAFT', ['QC_DRAFT', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['QC_DRAFT', ['BUILDING_TIMELINE', 'RENDERING_FINAL', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['RENDERING_FINAL', ['QC_FINAL', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['QC_FINAL', ['UPLOADING_PRIVATE', 'WAITING_FINAL_APPROVAL', 'BUILDING_TIMELINE', 'FINALIZING_SCRIPT', 'STORYBOARD_PROVISIONAL', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['UPLOADING_PRIVATE', ['WAITING_YOUTUBE_PROCESSING', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['WAITING_YOUTUBE_PROCESSING', ['WAITING_FINAL_APPROVAL', 'BLOCKED_EXCEPTION', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['WAITING_FINAL_APPROVAL', ['UPLOADING_PRIVATE', 'SCHEDULED', 'PUBLISHED', 'AWAITING_MANUAL_STUDIO_ACTION', 'BUILDING_TIMELINE', 'FINALIZING_SCRIPT', 'STORYBOARD_PROVISIONAL', 'WAITING_FOR_DOWNLOADS', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['SCHEDULED', ['PUBLISHED', 'PAUSED', 'CANCELLED', 'FAILED']],
  ['PUBLISHED', ['ANALYTICS_ACTIVE', 'ARCHIVED']],
  ['ANALYTICS_ACTIVE', ['ARCHIVED']],
  ['PAUSED', PROJECT_STATES.filter(state => !['PAUSED', 'ARCHIVED'].includes(state))],
  ['BLOCKED_EXCEPTION', PROJECT_STATES.filter(state => !['BLOCKED_EXCEPTION', 'ARCHIVED'].includes(state))],
  ['AWAITING_MANUAL_STUDIO_ACTION', ['SCHEDULED', 'PUBLISHED', 'WAITING_FINAL_APPROVAL', 'CANCELLED', 'FAILED']],
  ['CANCELLED', ['ARCHIVED']],
  ['FAILED', ['ARCHIVED']],
  ['ARCHIVED', []]
];

export const PROJECT_TRANSITIONS = new Map<ProjectState, ReadonlySet<ProjectState>>(
  entries.map(([from, targets]) => [from, new Set(targets)])
);

export function canTransitionProject(from: ProjectState, to: ProjectState): boolean {
  return from === to || Boolean(PROJECT_TRANSITIONS.get(from)?.has(to));
}

export function assertProjectTransition(from: ProjectState, to: ProjectState): void {
  if (!canTransitionProject(from, to)) throw new Error(`Invalid project transition: ${from} -> ${to}`);
}
